<?php

namespace AdminBundle\Repository;

/**
 * MachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineRepository extends \Doctrine\ORM\EntityRepository
{
}
