admin_accueil:
    path:      /admin
    defaults:  { _controller: AdminBundle:Admin:index}
    requirements:
        page: \d*

platform_view:
    path:      /admin/{id}
    defaults:  { _controller: AdminBundle:Admin:view }
    requirements:
        id: \d+

platform_add:
  path:      /add/machine
  defaults:  { _controller: AdminBundle:Admin:add}
  requirements:
      page: \d*

platform_edit:
  path:      /edit/{id}
  defaults:  { _controller: AdminBundle:Admin:edit}
  requirements:
      page: \d*

platform_listview:
  path:      /list
  defaults:  { _controller: AdminBundle:Admin:list}
  requirements:
      page: \d*

platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: AdminBundle:Admin:delete }
    requirements:
        id: \d+

ens_view:
    path:      /ens/{id}
    defaults:  { _controller: AdminBundle:Enseignant:view }
    requirements:
        id: \d+

ens_add:
  path:      /add/ens
  defaults:  { _controller: AdminBundle:Enseignant:add}
  requirements:
      page: \d*

ens_edit:
  path:      /editens/{id}
  defaults:  { _controller: AdminBundle:Enseignant:editens}
  requirements:
      page: \d*

ens_listview:
  path:      /listens
  defaults:  { _controller: AdminBundle:Enseignant:listens}
  requirements:
      page: \d*

ens_delete:
    path:      /deleteens/{id}
    defaults:  { _controller: AdminBundle:Enseignant:deleteens }
    requirements:
        id: \d+
