admin_accueil:
    path:      /admin
    defaults:  { _controller: AdminBundle:Admin:index}
    requirements:
        page: \d*

platform_view:
    path:      /admin/{id}
    defaults:  { _controller: AdminBundle:Admin:view }
    requirements:
        id: \d+

platform_add:
  path:      /add/machine
  defaults:  { _controller: AdminBundle:Admin:add}
  requirements:
      page: \d*

platform_listview:
  path:      /list
  defaults:  { _controller: AdminBundle:Admin:list}
  requirements:
      page: \d*

platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: AdminBundle:Admin:delete }
    requirements:
        id: \d+
